/*
-- Query: SELECT* FROM Victim_Profile
LIMIT 0, 1000

-- Date: 2021-12-02 15:47
*/
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (1,'Heather','Hill',16,'Atlanta','GA','Black',5.5,126.9,'Black','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (2,'Ana','Flores',21,'Bowie','MD','Hispanic',5.6,137.2,'Brown','Blue','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (3,'Molly','Hicks',20,'Siliver Spring','MD','White',5.4,149.3,'Blonde','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (4,'Sabrina','Springs',19,'Raliegh','NC','White',5.6,153.8,'Black','Blue','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (5,'Krystal','Fields',22,'Greensboro','NC','Black',5.6,167.2,'Black','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (6,'Hannah','Baker',15,'Hyattville','MD','White',5.8,159.2,'Brown','Blue','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (7,'Anderson','Lang',22,'Greensboro','NC','Asian',5.9,150.2,'Brown','Brown','False');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (8,'Kiara','Webster',24,'Nashville','TN','White',5.4,147.9,'Blonde','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (9,'Shelby','Dane',25,'Laurel','MD','Black',5.8,127.1,'Black','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (10,'Jordan','Fields',22,'Savannah','GA','White',5.2,149.7,'Blonde','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (11,'Rebecca','Shane',22,'Buies Creek','NC','White',5.6,135.6,'Brown','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (12,'Tesa','Tark',21,'Charlotte','NC','Hispanic',5.4,137.2,'Black','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (13,'Emma','Walker',24,'Gaithersburg','MD','White',5.3,152.1,'Blonde','Blue','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (14,'Dorain','Smith',25,'San Diego','CA','Black',5.4,145.1,'Black','Brown','True');
INSERT INTO `` (`idVictim_Profile`,`Victim_FirstName`,`Victim_LastName`,`Victim_Age`,`Victim_City`,`Victim_State`,`Victim_Race`,`Victim_Height`,`Victim_Weight`,`Victim_HairColor`,`Victim_EyeColor`,`Victim_isaFemale`) VALUES (15,'Lindsey','Blake',21,'Rockville','MD','White',5.2,137.8,'Brown','Blue','True');
